### PR TITLE
updated for real fetch call

### PR DESCRIPTION
**Pull request by Adam-Meza**
Where did the template go???

Ok so this push updated the fetches so theyre pulling the real data from BE. Had to update some of the components to reflect the changes in data structure. also the dispatch changed slightly but not super impactfully. wanted to push it up before making any more drastic changes.

### CODE REVIEW

**Comment by Adam-Meza** [comment]
ok so this is failing because of the babel issue which im not sure how to fix but isnt breaking anything

**Comment by sdmisra** [comment]
> ok so this is failing because of the babel issue which im not sure how to fix but isnt breaking anything

https://stackoverflow.com/questions/76435306/babel-preset-react-app-is-importing-the-babel-plugin-proposal-private-propert

this looks to be the sort of fix we can use, we can do it together after standup and then branch off again from there

**Comment by priscillaapaxton** [comment]
> > ok so this is failing because of the babel issue which im not sure how to fix but isnt breaking anything
> 
> https://stackoverflow.com/questions/76435306/babel-preset-react-app-is-importing-the-babel-plugin-proposal-private-propert
> 
> this looks to be the sort of fix we can use, we can do it together after standup and then branch off again from there

I saw this solution that Shane posted as well. I had actually added it to the project board so we could talk about it. I wanted to discuss what every aspect of the install meant. We can work on this today

**Comment by priscillaapaxton** [comment]
Adam, I tried to review the files you changed, but I couldn't see any of the files in src and my github tab crashed because there were so many files that had to load

**Pull request closed without merging**
